kitchen_sentences = [
    "Also, yesterday I noticed I still had 300g of apples and 500g of bananas at home, which are really good for my family’s health, and I thought next time I could cook them with 10g of salt to make a delicious meal, and I also couldn’t forget to prepare 50g of chocolate that my daughter loves the most.",
    "Besides, last week I learned how to make scrambled eggs with tomatoes, and after finishing my meal tomorrow I plan to buy some fresh ingredients along with 2 bottles of milk and 200g of bread for breakfast that my husband and I will eat the next morning, it’s so nice that tomorrow is finally the weekend.",
    "And, last night I found 250g of chicken breast and 300g of broccoli in the fridge, and I believe next weekend I can stir-fry them with 6g of salt and a little garlic to make a light and healthy dinner for the whole family.",
    "What’s more, a few days ago I bought 400g of beef and 150g of onions, and I’m thinking next Saturday I will use them to cook noodles with 8g of soy sauce and 4g of sugar to make the taste just perfect.",
    "Plus, yesterday I watched a cooking video and learned how to make vegetable salad, and next Monday I plan to prepare 150g of cucumber, 100g of tomato, 50g of corn and 10ml of olive oil to make a fresh and healthy salad.",
    "On top of that, last week I stored 250g of fish and 120g of ginger at home, and I think next Sunday I can steam them with 5g of salt and some green onions for a simple and delicious dinner.",
    "And, yesterday I saw a nice pancake recipe online, and tomorrow morning I will prepare 200g of flour, 2 eggs, 150ml of milk and 10g of sugar to make a warm and sweet breakfast for everyone.",
    "Also, last time I cooked I still had 180g of tofu and 120g of green beans left, and I believe next weekday I can stir-fry them with 4g of salt and a little oil for a quick and healthy dish.",
    "Besides, a few days ago I learned how to make egg drop soup, and next cold day I will use 2 eggs, 500ml of water and 3g of salt to cook a warm and comforting bowl of soup.",
    "What’s more, yesterday I found 350g of pork and 150g of bell peppers in the kitchen, and I plan to cook them next Friday with 7g of oyster sauce and 3g of sugar, a dish my whole family enjoys a lot.",
    "Plus, last week I bought plenty of fruits, and next afternoon I will make fruit salad with 200g of watermelon, 100g of grapes, 150g of oranges and 20g of yogurt for a healthy snack.",
    "And, yesterday I discovered 220g of cabbage and 80g of mushrooms, and I think next time I’m tired I will boil them with water and 4g of salt for a simple and light soup.",
    "On top of that, last Monday I learned how to make fried toast, and tomorrow morning I will use 300g of bread, 50g of butter and 2 eggs to make a quick and tasty breakfast.",
    "Also, a few days ago I prepared 160g of shrimp and 140g of corn, and next weekend I will use them to make fried rice with 6g of salt and some black pepper.",
    "Besides, yesterday I found a cookie recipe, and next weekend I will bake some cookies with 180g of flour, 80g of sugar, 50g of butter and 1 egg for my children.",
    "What’s more, last week I bought 300g of lamb and 120g of carrots, and I plan to stew them next Sunday with 8g of salt and some special spices for a warm meal.",
    "Plus, yesterday I learned the correct way to boil eggs, and next morning I will cook 6 eggs with 1 liter of water and a little salt to make them easy to peel.",
    "And, last time I shopped I got 250g of celery and 100g of walnuts, and I think next weekday I can stir-fry them with 4g of oil and 3g of salt for a crispy dish.",
    "On top of that, a few days ago I saw a milk pudding tutorial, and next Saturday I will make it with 500ml of milk, 30g of sugar and 15g of gelatin for a smooth dessert.",
    "Also, yesterday I still had 280g of squid and 90g of onions left, and I believe next Friday I can fry them with 6g of soy sauce and some garlic for a nice seafood dish.",
    "Besides, last week I learned how to make vegetable porridge, and next morning I will cook it with 150g of rice, 100g of pumpkin, 800ml of water and 3g of salt.",
    "What’s more, yesterday I found 190g of asparagus and 70g of bacon in the fridge, and I plan to bake them next weekend with 4g of oil and some black pepper.",
    "Plus, a few days ago I learned to make healthy lemon water, and next hot day I will prepare 1 lemon, 500ml of warm water and 10g of honey for a refreshing drink.",
    "And, last week I bought 320g of duck and 110g of potatoes, and I will braise them next Saturday with 7g of sugar and 5g of salt for a rich and tasty dinner.",
    "On top of that, yesterday I learned how to make tomato soup, and next weekday I will cook it with 300g of tomatoes, 1 egg, 4g of salt and a little cooking oil.",
    "Also, last time I cooked I had 210g of cauliflower and 130g of chicken left, and I think next Monday I can stir-fry them with 5g of salt and some ginger.",
    "Besides, a few days ago I planned a healthy breakfast, and tomorrow morning I will make oatmeal with 120g of oats, 300ml of milk and 20g of raisins.",
    "What’s more, yesterday I prepared 240g of cod and 80g of green onions, and next Sunday I will steam them with 4g of salt and some ginger for a tender dish.",
    "Plus, last week I wanted to make fried noodles, and next lunchtime I will use 300g of noodles, 150g of cabbage, 100g of pork and 6g of soy sauce.",
    "And, a few days ago I found 170g of yam and 120g of red dates, and I will cook them next weekend with water and 15g of rock sugar for a sweet soup.",
    "On top of that, yesterday I practiced making scrambled eggs with tomatoes, and next dinner I will use 2 tomatoes, 3 eggs, 4g of salt and 5g of oil for a classic dish.",
    "Also, last week I bought 260g of mussels and 90g of garlic, and I plan to stir-fry them next Friday with 6g of butter and some black pepper.",
    "Besides, yesterday I thought about making a light salad, and next afternoon I will prepare 200g of lettuce, 100g of tuna and 10ml of salad dressing.",
    "What’s more, a few days ago I bought 310g of ribs and 140g of corn, and next Sunday I will boil them with 1 liter of water and 7g of salt for a sweet soup.",
    "Plus, last week I learned how to fry dumplings, and next weekend I will cook 15 dumplings with 10g of oil and a little water to make them crispy.",
    "And, yesterday I saw a banana pancake recipe, and tomorrow morning I will make it with 2 bananas, 100g of flour, 1 egg and 100ml of milk.",
    "On top of that, a few days ago I prepared 230g of kale and 60g of almonds, and next weekday I will mix them with 8ml of olive oil and 3g of salt for a healthy salad.",
    "Also, last time I cooked I had 180g of sausage and 200g of green beans left, and I will stir-fry them next Monday with 5g of salt and some garlic.",
    "Besides, yesterday I planned to make red bean soup, and next weekend I will cook it with 150g of red beans, 800ml of water and 30g of sugar for dessert.",
    "What’s more, a few days ago I learned how to make steamed bread, and next Saturday I will make it with 300g of flour, 5g of yeast and 180ml of warm water.",
    "Plus, last week I bought 290g of tuna and 120g of avocado, and I will make sandwiches next weekday with 4 slices of bread and a little mayonnaise.",
    "And, yesterday I thought about making pumpkin porridge, and tomorrow morning I will cook it with 120g of rice, 200g of pumpkin and 700ml of water.",
    "On top of that, a few days ago I prepared 160g of bamboo shoots and 140g of pork, and I will stir-fry them next Friday with 6g of oyster sauce and 3g of sugar.",
    "Also, last week I bought 340g of salmon and 100g of lemon, and next weekend I will bake it with 5g of salt and some black pepper for a healthy meal.",
    "Besides, yesterday I found a nice jam recipe, and next Sunday I will make strawberry jam with 200g of strawberries, 100g of blueberries and 50g of sugar.",
    "What’s more, a few days ago I still had 220g of lotus root and 130g of ribs left, and I will boil them next weekend with water and 6g of salt for a light soup.",
    "Plus, last week I learned how to make homemade fries, and next Saturday I will cook them with 300g of potatoes, 15g of oil and a little salt.",
    "And, yesterday I prepared 140g of cheese and 200g of macaroni, and I will make cheese macaroni next weekday with 100ml of milk for my kid.",
    "On top of that, a few days ago I planned to make green juice, and next morning I will make it with 100g of cucumber, 80g of celery and 300ml of water.",
    "Also, last week I bought many healthy ingredients, and I believe next month I can try more new recipes to make my family’s meals more delicious and nutritious."
]

wine_sentences = [
    "Although I had bought many low-sugar wines last year, I still hadn't found any sweet ones from France that were under 100 yuan.",
    "Even though I had checked the tax rate several times before, I still couldn't figure out how much total tax I had paid for my wines last month.",
    "Since I had heard there were vegan wines in the shop, I had wondered which of them were low in calories and from Italy.",
    "Not only had I looked for spicy-tasting wines before, but I had also wanted to exclude all expensive ones from my old shopping list.",
    "While I had been adding a Spanish wine to the catalog last week, I had forgotten to fill in its nutritional characteristics completely.",
    "Because I had never liked bitter drinks, I had filtered all bitter wines out before I made my final purchase.",
    "Even if I had known the price of a single wine, I wouldn't have calculated the total cost of my cart correctly that day.",
    "Since I had suffered from allergies before, I had always checked the allergen information of every wine I bought.",
    "Although I had only bought mild-tasting wines in the past, I had still checked their protein and fat content every time.",
    "While I had been checking discounted products last month, I had found many cheap wines from Germany.",
    "Not only had I summed the nutrition of my cart before, but I had also calculated the total tax I needed to pay.",
    "Because I had wanted high-fiber drinks last year, I had searched by nutritional characteristic but got many salty results.",
    "Even though I had found a good wine from Portugal, I had still compared its tax rate with others before buying.",
    "Since I had cleared my cart several times before, I had also deleted some old records from the product list.",
    "Although I had asked for low-sodium wine before, the system had only shown me umami-tasting ones without price details.",
    "While I had been computing the total cost last week, I had realized I didn't know the discount of the sparkling wine.",
    "Not only had I looked for gluten-free wines before, but I had also wanted sour ones between 150 and 300 yuan.",
    "Because I had added two white wines to my cart last time, I had summed their calories to see if they were too high.",
    "Even if I had seen wines from Argentina before, I hadn't decided which ones had no additives and were savory.",
    "Since I had updated a wine's price last month, I had also changed its discount and tax rate together.",
    "Although I had removed some items from my cart before, I hadn't known how to delete a product from the system.",
    "While I had looked for sugar-free wine in the past, I had also checked its carbs per 100 grams carefully.",
    "Not only had I checked my cart items before, but I had also recorded every original and discounted price.",
    "Because I had wanted high-calcium drinks last year, I had filtered by nutrition but ignored their country of origin.",
    "Even though I had bought wines from Chile before, I had always chosen low-fat ones to control my total cost.",
    "Since I had not known the discount of that red wine, I had failed to compute the final amount correctly.",
    "Although I had added a new wine to the catalog before, I had missed its allergens and nutrition tags.",
    "While I had searched by taste last month, I had found many sweet wines that were also on discount.",
    "Not only had I deleted a wine from the list before, but I had also removed its records from old carts.",
    "Because I had calculated cart tax several times, I had learned every wine's tax rate and quantity.",
    "Even if I had seen nutrition facts before, I hadn't compared them across different countries and categories.",
    "Since I had wanted low-calorie wine in the past, I had avoided anything bitter or spicy.",
    "Although I had searched wines by country before, I hadn't combined taste and nutrition filters.",
    "While I had added wine to my cart last time, I had added too much and had to remove part of it later.",
    "Not only had I summed cart nutrition before, but I had also checked sugar, sodium, and fiber separately.",
    "Because many discounts had changed last year, I had updated prices and discount factors one by one.",
    "Even though I had bought savory wines before, I had always made sure they were sugar-free.",
    "Since I had not found my ideal wine last time, I had planned to add it myself later.",
    "Although I had checked price ranges before, I hadn't known which ones were really discounted.",
    "While I had calculated tax last month, I had noticed different wines used different tax rates.",
    "Not only had I looked at discounted wines before, but I had also filtered out high-sugar ones.",
    "Because I had wanted high-protein wine in the past, I had checked fat and carbs before buying.",
    "Even if I had known a wine's origin before, I hadn't decided without taste and discount info.",
    "Since I had cleared my cart yesterday, I would need to add the same items again next time.",
    "Although I had searched by taste and nutrition before, the system hadn't shown cart options.",
    "While I had checked discount rates last week, I hadn't realized they would affect tax so much.",
    "Not only had I checked tax rates before, but I had also compared them across different countries.",
    "Because I had disliked umami taste before, I had excluded all umami wines from my old lists.",
    "Even though I had calculated total cost before, I hadn't separated price, discount, and tax.",
    "Since I will buy wine for a party next month, I will add multiple types and check total nutrition."
]

retail_sentences = [
    "Last time I bought St Michel Le Sablé de Reims Coconut, I didn’t check its detailed nutrition information at that time.",
    "I will buy St Michel La Galette All Butter next week because I really like butter flavored cookies.",
    "When I shopped last month, I added St Michel Le Petit Beurre to my cart but I removed it before I paid the bill.",
    "I will try St Michel Le Palmier Crispy Caramel tomorrow since I love caramel flavored snacks.",
    "During my last purchase, I didn’t notice that Crispy Cups Happy (Multicolor) contains wheat as an allergen.",
    "I will buy Crispy Cups Classic next time to compare it with the colorful version I had before.",
    "When I bought snacks last week, I chose Crispy Cups Cookies & Cream for its creamy taste.",
    "I will buy Highland Speciality Shortbread Assortment next month as a gift for my friend.",
    "Last time I tried Dukan Nutrition Pour Tous Chocolate, I was surprised by its high protein content.",
    "I will choose Dukan Nutrition Pour Tous Original next week since I prefer the original flavor.",
    "During my previous shopping, I bought Highland Speciality Shortbread Teddy Bear for my little niece.",
    "I will buy Choco Fit Hazelnut next time even though it is a little more expensive than other cookies.",
    "When I visited the store last weekend, I saw Choco Fit Chocolate but I didn’t buy it at that time.",
    "I will try Grisbi Limone Citron tomorrow because I want something sweet and sour.",
    "Last time I bought Grisbi Nocciola Hazelnut, I didn’t know it contains nuts until I read the label.",
    "I will choose Grisbi Chocolate next week since I am in the mood for chocolate cookies.",
    "During my last purchase, I bought St Michel Milk Chocolate Cookie because of its reasonable price.",
    "I will try St Michel Dark Chocolate Cookie next month for its special bitter sweet taste.",
    "When I shopped two days ago, I picked Dukan Chocolate Bar as a small snack for work.",
    "I will buy Choco Fit Lemon next time to try a lighter flavor of this brand.",
    "Last week I bought Pallets Biscuits from Japan and I thought its taste was very unique.",
    "I will choose Crispy Cups Choco Vanilla next week since I love both chocolate and vanilla.",
    "During my last shopping trip, I bought Crispy Cups Strawberry for its bright color and sweet taste.",
    "I will buy St Michel Caramel Filled Cookies tomorrow because I like filled cookies very much.",
    "When I bought snacks last month, I chose Dukan Chocolate Chip Cookie for its low carb feature.",
    "I will buy Highland Speciality Shortbread Mini next time since it is easy to carry around.",
    "Last time I tried Grisbi Chocolate Hazelnut, I really enjoyed the nutty chocolate flavor.",
    "I will choose Crispy Cups Vanilla next week to try the simplest flavor of this series.",
    "During my previous purchase, I bought Desobry Speculoos from Denmark and I liked it a lot.",
    "I will buy Dukan Chocolate Wafer next month to try more products from this brand.",
    "When I shopped last holiday, I picked Crispy Cups Mint because I wanted a fresh taste.",
    "I will buy Bahlsen from Germany next time to try a new type of cookie.",
    "Last time I bought snacks, I compared St Michel series but I still couldn’t decide quickly.",
    "I will check the calories of Dukan series products before I buy them next week.",
    "During my last order, I added too many Crispy Cups and I had to remove some later.",
    "I will look for all French cookies like St Michel when I go shopping tomorrow.",
    "When I bought Italian Grisbi last week, I didn’t check its sugar content carefully.",
    "I will buy Scottish shortbread next month because I tried it once and loved it.",
    "Last time I bought snacks, I didn’t notice that many products contain milk allergens.",
    "I will check the tax rate of imported cookies before I add them to my cart next time.",
    "During my last purchase, I bought high protein Dukan cookies for my fitness plan.",
    "I will avoid high sugar snacks like some Crispy Cups when I shop next week.",
    "When I bought Choco Fit last month, I thought its price was higher than other brands.",
    "I will buy low fat cookies like St Michel Le Sablé de Reims Coconut next time.",
    "Last week I bought several cookies but I forgot to check their country of origin.",
    "I will buy Desobry Speculoos again next time because of its special nutty taste.",
    "During my last shopping, I cleared my cart and finally chose only Bahlsen cookies.",
    "I will look for gluten free snacks next time although most cookies contain gluten.",
    "When I bought Dukan Chocolate Wafer last time, I didn’t calculate the total price.",
    "I will buy all my favorite cookies including Grisbi and St Michel next weekend."
]

restaurant_sentences = [
    "Last time I ate here, I tried several kinds of pasta but I didn’t remember their exact prices at that time.",
    "I will come to this restaurant with my friends next week and I plan to order some smoky flavored steaks then.",
    "When I visited last month, I had checked the allergens of the salads but I still forgot to note them down.",
    "I will choose some low calorie dishes for my dinner tomorrow since I have been keeping my diet recently.",
    "During my previous visit, I added a pizza to my order but I removed it before I finally paid the bill.",
    "Next time when I come here, I will first look at all the discounted dishes before making my decision.",
    "I ate a savory sandwich here last week and I thought its price was quite reasonable for the portion.",
    "I will check the nutrition information of the handmade bread before I order it for my breakfast tomorrow.",
    "When I came for lunch two days ago, I didn’t notice that some dishes had already been removed from the menu.",
    "I will order a set meal next time because I believe it will be more cost-effective than ordering separately.",
    "Last time I ordered some cold cuts, I didn’t calculate the total price until the waiter told me.",
    "I will avoid spicy food when I come next week since my stomach won’t feel very comfortable these days.",
    "During my last visit, I tried to update my order several times but I still ordered the wrong dishes in the end.",
    "I will look for high protein dishes next time because I need to take in more protein after my workout.",
    "When I ate here last weekend, I didn’t know that the restaurant had newly added some vegan options to the menu.",
    "I will clear my order and start over if I can’t find suitable dishes when I come tomorrow.",
    "Last time I ordered cheese and olives, I didn’t check its sodium content and I felt a little thirsty after that.",
    "I will filter the dishes by price range next time so that I won’t spend too much on a single meal.",
    "When I visited last month, the restaurant had just updated the discount of several popular pasta dishes.",
    "I will ask for the taste profile of every dish I order next time to avoid food I don’t like.",
    "During my previous dinner here, I ordered too many dishes and I couldn’t finish all of them at all.",
    "I will choose gluten free food next time because one of my family members is allergic to gluten.",
    "Last time I ate antipasti and snacks here, I thought their taste was mild and very suitable for children.",
    "I will summarize the total nutrition of my order before I pay next time to control my daily intake.",
    "When I came for dinner last week, I didn’t find any set meals that contained the dishes I wanted most.",
    "I will pay attention to dishes with no additives when I order next time for the sake of my health.",
    "During my last visit, I had checked the tax of my order but I still didn’t understand how it was calculated.",
    "I will order high calcium dishes next time because I want to supplement more calcium in my recent diet.",
    "When I ate here two weeks ago, I added a steak to my order but I forgot to check its fat content.",
    "I will look for sugar free desserts if they are available when I come to this restaurant tomorrow.",
    "Last time I visited, I found the price of handmade bread had been raised compared to before.",
    "I will order some high omega3 food next time since I heard it is really good for health.",
    "During my previous meal here, I didn’t notice that some dishes were only provided at a limited time.",
    "I will check the detailed composition of the set meal before I add it to my order next time.",
    "When I came for lunch last month, I ordered salads without knowing that they contained allergens I should avoid.",
    "I will only order dishes in the Pizza category next time because I really miss the taste here.",
    "Last time I ate here, I tried to calculate the total cost myself but the result was different from the bill.",
    "I will ask the waiter to recommend umami flavored dishes when I come to have dinner next week.",
    "During my last visit, I didn’t know that the restaurant could update the dish price without prior notice.",
    "I will choose low sodium food for my parents when I bring them here next time.",
    "When I visited last week, I had already cleared my order but I still didn’t decide what to eat in the end.",
    "I will check the fiber content of every dish I order tomorrow because I need more dietary fiber.",
    "Last time I ordered sandwiches here, I didn’t realize that they were on discount until I paid the bill.",
    "I will find all the dishes under my favorite category first when I come to this restaurant next month.",
    "During my previous dinner, I ordered too many high fat dishes and I felt guilty after the meal.",
    "I will add more vegetables to my order next time so that my meal can be more balanced and healthy.",
    "When I came here last holiday, the restaurant had just launched several new set meals for customers.",
    "I will avoid sour food next time because I don’t really like such taste in my daily meals.",
    "Last time I ordered steaks here, I didn’t check their nutrition facts and just ate them directly.",
    "I will make a whole new order when I come tomorrow instead of repeating what I ordered before."
]

order_sentences = [
    "Also, yesterday I noticed I still had a craving for the Margherita pizza from Annie Italian Restaurant, and I thought next time I could check its 38 yuan price, and I also couldn’t forget to prepare 50g of chocolate that my daughter loves the most.",
    "Besides, last week I learned how the tax rate works for the Greek Village Roast Chicken Leg, and after finishing my meal tomorrow I plan to buy some fresh ingredients along with 2 bottles of milk and 200g of bread for breakfast.",
    "And, last night I found 250g of Grilled Octopus in my memory from Mediterranean Greek Restaurant, and I believe next weekend I can order them with 6g of salt and a little garlic to make a light and healthy dinner.",
    "What’s more, a few days ago I bought a voucher for the Australian selected Ribeye, and I’m thinking next Saturday I will use them to cook noodles with 8g of soy sauce and 4g of sugar to make the taste just perfect.",
    "Plus, yesterday I watched a cooking video about Feta & Tomato Spaghetti, and next Monday I plan to prepare 150g of cucumber, 100g of tomato, 50g of corn and 10ml of olive oil to make a fresh and healthy salad.",
    "On top of that, last week I stored 250g of Grilled Fish and 120g of ginger at home, and I think next Sunday I can steam them with 5g of salt and some green onions for a simple and delicious dinner.",
    "And, yesterday I saw a nice pancake recipe online, and tomorrow morning I will prepare 200g of flour, 2 eggs, 150ml of milk and 10g of sugar to make a warm and sweet breakfast for everyone.",
    "Also, last time I cooked I still had 180g of Salame Milano and 120g of green beans left, and I believe next weekday I can stir-fry them with 4g of salt and a little oil for a quick and healthy dish.",
    "Besides, a few days ago I learned how to make egg drop soup, and next cold day I will use 2 eggs, 500ml of water and 3g of salt to cook a warm and comforting bowl of soup.",
    "What’s more, yesterday I found 350g of Mortadella and 150g of bell peppers in the kitchen, and I plan to cook them next Friday with 7g of oyster sauce and 3g of sugar, a dish my whole family enjoys a lot.",
    "Plus, last week I bought plenty of fruits, and next afternoon I will make fruit salad with 200g of watermelon, 100g of grapes, 150g of oranges and 20g of yogurt for a healthy snack.",
    "And, yesterday I discovered 220g of cabbage and 80g of mushrooms, and I think next time I’m tired I will boil them with water and 4g of salt for a simple and light soup.",
    "On top of that, last Monday I learned how to make fried toast, and tomorrow morning I will use 300g of bread, 50g of butter and 2 eggs to make a quick and tasty breakfast.",
    "Also, a few days ago I prepared 160g of shrimp and 140g of corn, and next weekend I will use them to make fried rice with 6g of salt and some black pepper.",
    "Besides, yesterday I found a cookie recipe, and next weekend I will bake some cookies with 180g of flour, 80g of sugar, 50g of butter and 1 egg for my children.",
    "What’s more, last week I bought 300g of lamb and 120g of carrots, and I plan to stew them next Sunday with 8g of salt and some special spices for a warm meal.",
    "Also, yesterday I wondered if the Lasagne at Annie Italian Restaurant was still on discount, and I thought next time I could check the price list, and I also couldn’t forget to prepare 50g of chocolate.",
    "Besides, last week I learned how the nutritional tags work for the Greek Salad, and after finishing my meal tomorrow I plan to buy some fresh ingredients along with 2 bottles of milk.",
    "And, last night I found 250g of Mediterranean Grilled Prawns in my wishlist, and I believe next weekend I can order them with 6g of salt and a little garlic to make a light dinner.",
    "What’s more, a few days ago I bought a gift card for the Moussaka, and I’m thinking next Saturday I will use them to cook noodles with 8g of soy sauce and 4g of sugar.",
    "Plus, yesterday I watched a cooking video about Tzatziki, and next Monday I plan to prepare 150g of cucumber, 100g of tomato, 50g of corn and 10ml of olive oil.",
    "On top of that, last week I stored 250g of Spanakopita and 120g of ginger at home, and I think next Sunday I can steam them with 5g of salt and some green onions.",
    "And, yesterday I saw a nice pancake recipe online, and tomorrow morning I will prepare 200g of flour, 2 eggs, 150ml of milk and 10g of sugar for breakfast.",
    "Also, last time I cooked I still had 180g of Salame Milano and 120g of green beans left, and I believe next weekday I can stir-fry them with 4g of salt and a little oil.",
    "Besides, a few days ago I learned how to make egg drop soup, and next cold day I will use 2 eggs, 500ml of water and 3g of salt to cook a warm bowl of soup.",
    "What’s more, yesterday I found 350g of Mortadella and 150g of bell peppers in the kitchen, and I plan to cook them next Friday with 7g of oyster sauce and 3g of sugar.",
    "Plus, last week I bought plenty of fruits, and next afternoon I will make fruit salad with 200g of watermelon, 100g of grapes, 150g of oranges and 20g of yogurt.",
    "And, yesterday I discovered 220g of cabbage and 80g of mushrooms, and I think next time I’m tired I will boil them with water and 4g of salt for a light soup.",
    "On top of that, last Monday I learned how to make fried toast, and tomorrow morning I will use 300g of bread, 50g of butter and 2 eggs to make a tasty breakfast.",
    "Also, a few days ago I prepared 160g of shrimp and 140g of corn, and next weekend I will use them to make fried rice with 6g of salt and some black pepper.",
    "Besides, yesterday I found a cookie recipe, and next weekend I will bake some cookies with 180g of flour, 80g of sugar, 50g of butter and 1 egg for my kids.",
    "What’s more, last week I bought 300g of lamb and 120g of carrots, and I plan to stew them next Sunday with 8g of salt and some special spices.",
    "Also, yesterday I noticed I still had a craving for the Buffalo mozzarella margherita pizza, and I thought next time I could order it with extra cheese, and I also couldn’t forget to prepare 50g of chocolate.",
    "Besides, last week I learned how the tax rate works for the Australian imported M7 Wagyu sirloin, and after finishing my meal tomorrow I plan to buy some fresh ingredients.",
    "And, last night I found 250g of Grilled salmon in my memory, and I believe next weekend I can order them with 6g of salt and a little garlic to make a healthy dinner.",
    "What’s more, a few days ago I bought a voucher for the Tiramisu, and I’m thinking next Saturday I will use them to cook noodles with 8g of soy sauce and 4g of sugar.",
    "Plus, yesterday I watched a cooking video about Cheesecake, and next Monday I plan to prepare 150g of cucumber, 100g of tomato, 50g of corn and 10ml of olive oil.",
    "On top of that, last week I stored 250g of Mixed cold cuts plank and 120g of ginger at home, and I think next Sunday I can steam them with 5g of salt and some green onions.",
    "And, yesterday I saw a nice pancake recipe online, and tomorrow morning I will prepare 200g of flour, 2 eggs, 150ml of milk and 10g of sugar to make a sweet breakfast.",
    "Also, last time I cooked I still had 180g of Cold cuts & cheese plate and 120g of green beans left, and I believe next weekday I can stir-fry them with 4g of salt and a little oil.",
    "Besides, a few days ago I learned how to make egg drop soup, and next cold day I will use 2 eggs, 500ml of water and 3g of salt to cook a comforting bowl of soup.",
    "What’s more, yesterday I found 350g of Tomato & garlic bruschetta and 150g of bell peppers in the kitchen, and I plan to cook them next Friday with 7g of oyster sauce and 3g of sugar.",
    "Plus, last week I bought plenty of fruits, and next afternoon I will make fruit salad with 200g of watermelon, 100g of grapes, 150g of oranges and 20g of yogurt for a snack.",
    "And, yesterday I discovered 220g of cabbage and 80g of mushrooms, and I think next time I’m tired I will boil them with water and 4g of salt for a simple soup.",
    "On top of that, last Monday I learned how to make fried toast, and tomorrow morning I will use 300g of bread, 50g of butter and 2 eggs to make a quick breakfast.",
    "Also, a few days ago I prepared 160g of shrimp and 140g of corn, and next weekend I will use them to make fried rice with 6g of salt and some black pepper.",
    "Besides, yesterday I found a cookie recipe, and next weekend I will bake some cookies with 180g of flour, 80g of sugar, 50g of butter and 1 egg for my children.",
    "What’s more, last week I bought 300g of lamb and 120g of carrots, and I plan to stew them next Sunday with 8g of salt and some special spices for a warm meal.",
    "Also, yesterday I noticed I still had a craving for the Seafood Lover's Set, and I thought next time I could order it with extra cheese, and I also couldn’t forget to prepare 50g of chocolate.",
    "Besides, last week I learned how the tax rate works for the Italian Classic Set, and after finishing my meal tomorrow I plan to buy some fresh ingredients along with 2 bottles of milk."
]